### ISSUE TITLE
failed to create containerd task: QMP command failed: Failed to connect socket /dev/drm_dp_aux0: Connection refused: unknown

### ISSUE THREAD

**Issue by robbmue** [robbmue/katanetes#12]
Pods starten nicht mit der cri katacontainer runtime

**Comment by robbmue** [comment]
Andere Worker, andere Devs:
`worker2: Message:      failed to create containerd task: QMP command failed: Failed to connect socket /dev/nvme0: Connection refused: unknown`

**Comment by nk-designz** [comment]
Issue #11 is working on this problem.
